version: '3'
services:
  backend:
    image: 'memanes688/node-auth-app:latest'
    ports:
      - '3000:3000'
    environment:
      DB_HOST: mysql
      DB_USER: 'appu'
      DB_PASSWORD: 'appu@Sagar135'
      DB_DATAASE: 'UserAuth'
    depends_on:
      - mysql
  mysql:
    image: 'mysql:5.7'
    environment:
      MYSQL_DATABASE: 'myDb'
      MYSQL_USER: 'appu'
      MYSQL_PASSWORD: 'appu@Sagar135'
      MYSQL_ROOT_PASSWORD: 'KittiGoddd@Sagar135'
    ports:
      - '3306:3306'
    volumes:
      - ./createdb.sql:/docker-entrypoint-initdb.d/createdb.sql
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: 
